### ISSUE TITLE
Export a function with void type

### ISSUE THREAD

**Issue by kYroL01** [mafintosh/napi-macros#1]
Hi @mafintosh .
First of all, thanks for the huge work.
I have a question: how to properly export a function with _void_ type ?
For example I have:

```
NAPI_METHOD (_finish) {
  finish();
}

NAPI_INIT() {
  NAPI_EXPORT_FUNCTION(_finish);
}
```

When I launch `npm install` I have this warning:

> warning: control reaches end of non-void function [-Wreturn-type]

I don't know how to solve, except the `NAPI_RETURN_[...]` macros in `NAPI_METHOD`, but it's not my case because finish is a C void function:  `void finish()` .

Thanks

**Comment by mafintosh** [comment]
All napi functions must return a napi_value, so you should always return one or do a `return NULL;` at the end of your function. Fell free to add a PR with that info :)

**Comment by mafintosh** [comment]
So your code should be

``` c
NAPI_METHOD (_finish) {
  finish();
  return NULL;
}

NAPI_INIT() {
  NAPI_EXPORT_FUNCTION(_finish);
}
```

**Comment by kYroL01** [comment]
Thank you so much for the answer
