### ISSUE TITLE
NAPI_UTF8() is stack based

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/napi-macros#6]
https://github.com/mafintosh/napi-macros/blob/da4aff3c2e6424aa64764845af107ea092566ff5/napi-macros.h#L101-L107

This is cool if you know that `size` is large enough to copy the string onto the stack. But can become a problem if the string from JavaScript is larger than `size` (which is compile time).

In `deltachat-node` we are using the following macro:

https://github.com/deltachat/deltachat-node/blob/0d62741e817592bf4671788458082ca836a22487/src/napi-macros-extensions.h#L5-L11

```c
#define NAPI_UTF8(name, val) \
  size_t name##_size = 0; \
  NAPI_STATUS_THROWS(napi_get_value_string_utf8(env, val, NULL, 0, &name##_size)); \
  char* name = malloc((name##_size + 1) * sizeof(char)); \
  size_t name##_len; \
  NAPI_STATUS_THROWS(napi_get_value_string_utf8(env, val, name, name##_size + 1, &name##_len)); \
  name[name##_size] = '\0';
```

This first gets the length of the string and then calls `malloc()` to allocate the string on the heap. Benefit here is that we can accept strings of any size, but downside is that the string _must_ be `free()`'d (unless the consumer can take ownership of the pointer that is).

Should we pull this in as a replacement or should we pull this in as another macro, e.g. `NAPI_UTF8_MALLOC()`?

**Comment by mafintosh** [comment]
This should be a new macro yes. Your name soudns good to me
